import type {
  Album,
  Announcement,
  Bhajan,
  Post,
  Profile,
  Registration,
  Resource,
  SaiEvent,
  SaiForm,
  SiteContent,
  Wing,
} from "./types";

/**
 * Demo content used when Supabase is not configured, so the whole site is
 * browsable out of the box. Dates are anchored to mid-2026.
 * Copy is written the way a centre volunteer would write it.
 */

export const CENTRE_ADDRESS = "2215 East Pender Street, Vancouver";

export const demoSiteContent: SiteContent = {
  intro:
    "Vancouver Sai Centre is a spiritual community located at 2215 East Pender Street, Vancouver. We gather for devotional singing, study, service, children’s education, and youth activities inspired by the teachings of Sri Sathya Sai Baba.",
  address: CENTRE_ADDRESS,
  babaTitle: "Who is Sri Sathya Sai Baba?",
  babaBody:
    "Sri Sathya Sai Baba (1926 to 2011) was a spiritual teacher born in Puttaparthi, a village in southern India. His central teaching is simple: love all, serve all. He taught that all faiths lead to the same goal, and asked his students to practise five values in daily life: love, truth, peace, right conduct, and non-violence.\n\nIn his name, his students around the world run free hospitals, schools, and drinking water projects. You can read more at sathyasai.org.",
  sssioTitle: "The Sri Sathya Sai International Organization",
  sssioBody:
    "The Sri Sathya Sai International Organization (SSSIO) has centres in more than 100 countries. Centres hold devotional meetings, run children’s classes, and organize community service. There are no fees and no conversion. Everyone is welcome to take part while practising their own faith.\n\nVancouver Sai Centre is part of SSSIO Canada. Learn more at sathyasai.org.",
  instagramHandle: "vancouver_sai_center",
  // Real names and contact details are added by the centre admins.
  // Empty lists show a setup prompt to admins and nothing to the public.
  contacts: [],
  bcGroups: [
    {
      id: "grp-abbotsford",
      name: "Abbotsford Sai Centre",
      address: "",
      contact: "",
      meetingTime: "",
      link: "",
    },
    {
      id: "grp-coquitlam",
      name: "Coquitlam Sai Centre",
      address: "",
      contact: "",
      meetingTime: "",
      link: "",
    },
  ],
};

export const demoPosts: Post[] = [
  {
    id: "post-guru-purnima",
    title: "Guru Purnima is on Wednesday, July 29",
    description:
      "Bhajans, a guest speaker, and a community dinner. Please register so we can plan food and seating.",
    body: "",
    imageUrl: "/images/gallery-festival.svg",
    videoUrl: null,
    instagramUrl: null,
    ctaLabel: "Register",
    ctaUrl: "/events/guru-purnima-2026",
    placements: ["featured", "announcements"],
    membersOnly: false,
    published: true,
    createdAt: "2026-07-01T09:00:00-07:00",
  },
  {
    id: "post-seva-drivers",
    title: "Drivers needed for the July 18 sandwich seva",
    description:
      "We are short three drivers to carry supplies downtown. Prep starts at 9 am at the centre kitchen.",
    body: "",
    imageUrl: "/images/gallery-seva.svg",
    videoUrl: null,
    instagramUrl: null,
    ctaLabel: "Sign up to help",
    ctaUrl: "/events/sandwich-seva-july",
    placements: ["featured", "announcements"],
    membersOnly: false,
    published: true,
    createdAt: "2026-07-03T08:30:00-07:00",
  },
  {
    id: "post-retreat",
    title: "Fall retreat registration closes September 20",
    description:
      "Three days at Loon Lake, October 9 to 11. Family cabins are nearly full. 68 of 120 spots are taken.",
    body: "",
    imageUrl: "/images/gallery-retreat.svg",
    videoUrl: null,
    instagramUrl: null,
    ctaLabel: "See retreat details",
    ctaUrl: "/events/fall-retreat-2026",
    placements: ["featured", "announcements", "portal"],
    membersOnly: false,
    published: true,
    createdAt: "2026-06-25T10:00:00-07:00",
  },
  {
    id: "post-sse",
    title: "SSE registration for the new school year is open",
    description:
      "Classes for children ages 6 to 17, Sunday afternoons at 3 pm. One registration per child per year.",
    body: "",
    imageUrl: null,
    videoUrl: null,
    instagramUrl: null,
    ctaLabel: "Register a child",
    ctaUrl: "/events/sse-classes",
    placements: ["announcements", "wing-education"],
    membersOnly: false,
    published: true,
    createdAt: "2026-06-15T10:00:00-07:00",
  },
];

export const demoWings: Wing[] = [
  {
    slug: "devotional",
    name: "Devotional Wing",
    tagline: "Bhajans and festivals",
    description:
      "We meet every Sunday at 5 pm for bhajans (devotional singing), followed by a short talk and prasadam. Song books are provided and no singing experience is needed. The devotional wing also organizes festival celebrations through the year, including Guru Purnima, Akhanda Bhajan, and Baba’s birthday in November.",
    activities: ["Sunday bhajans, 5 pm", "Festival celebrations", "Vedam chanting", "Jyoti meditation"],
  },
  {
    slug: "service",
    name: "Service Wing",
    tagline: "Helping around Vancouver",
    description:
      "Our regular projects include monthly sandwich making for the Downtown Eastside, a winter blanket and coat drive, and food bank support. Most projects welcome all ages, and children can take part with a parent. If you can drive, cook, or sort donations, there is a place for you.",
    activities: ["Monthly sandwich seva", "Winter blanket drive", "Food bank support", "Seniors’ home visits"],
  },
  {
    slug: "education",
    name: "Education Wing",
    tagline: "Classes for children and adults",
    description:
      "SSE (Sai Spiritual Education) classes run on Sunday afternoons for children ages 6 to 17, in four groups by age. Classes use stories, songs, activities, and a few minutes of silent sitting. Adults meet for a study circle on Wednesday evenings. Parents register children once per school year.",
    activities: ["SSE classes, Sundays 3 pm", "Study circle, Wednesdays 7:30 pm", "Parent sessions", "Public talks"],
  },
  {
    slug: "young-adults",
    name: "Young Adults",
    tagline: "Ages 18 to 35",
    description:
      "The young adults group meets on Friday evenings for study, music, and planning service projects. We also run an annual retreat and join regional YA events across BC. If you are new to Vancouver or new to the centre, this is an easy place to start.",
    activities: ["Friday meetings, 7 pm", "Annual YA retreat", "Service projects", "Bhajan practice"],
  },
];

// Anchored dates: "today" in demo terms is early July 2026.
export const demoEvents: SaiEvent[] = [
  {
    id: "ev-bhajans",
    slug: "sunday-bhajans",
    title: "Sunday Bhajans",
    description:
      "Our weekly gathering. An hour of devotional singing, a short talk, and prasadam. Doors open at 4:30 pm for jyoti meditation.\n\nNewcomers are always welcome. Song books are provided and no experience is needed. Please remove your shoes in the foyer.",
    bannerUrl: "/images/gallery-bhajan-hall.svg",
    startsAt: "2026-07-05T17:00:00-07:00",
    endsAt: "2026-07-05T18:30:00-07:00",
    location: `Vancouver Sai Centre, ${CENTRE_ADDRESS}`,
    capacity: null,
    registrationEnabled: false,
    volunteerSignupEnabled: false,
    livestreamUrl: "https://youtube.com/@vancouversaicentre/live",
    category: "devotional",
    recurrence: "weekly",
    recurrenceUntil: "2026-12-27",
    formId: null,
    registeredCount: 0,
    published: true,
  },
  {
    id: "ev-study-circle",
    slug: "study-circle",
    title: "Study Circle",
    description:
      "A weekly reading and discussion of Sathya Sai Baba’s teachings. This season we are reading Sadhana: The Inward Path. Come with your questions. You do not need to have read anything in advance.",
    bannerUrl: "/images/gallery-study.svg",
    startsAt: "2026-07-08T19:30:00-07:00",
    endsAt: "2026-07-08T21:00:00-07:00",
    location: "Vancouver Sai Centre, Library Room",
    capacity: null,
    registrationEnabled: false,
    volunteerSignupEnabled: false,
    livestreamUrl: null,
    category: "education",
    recurrence: "weekly",
    recurrenceUntil: "2026-12-23",
    formId: null,
    registeredCount: 0,
    published: true,
  },
  {
    id: "ev-ya-meeting",
    slug: "ya-weekly-meeting",
    title: "Young Adults Meeting",
    description:
      "Weekly meeting for ages 18 to 35. A check-in, a study theme, and planning for upcoming service projects. This month’s theme is Ceiling on Desires.",
    bannerUrl: "/images/gallery-ya.svg",
    startsAt: "2026-07-10T19:00:00-07:00",
    endsAt: "2026-07-10T20:30:00-07:00",
    location: "Vancouver Sai Centre, Upper Hall",
    capacity: null,
    registrationEnabled: false,
    volunteerSignupEnabled: false,
    livestreamUrl: null,
    category: "young-adults",
    recurrence: "weekly",
    recurrenceUntil: "2026-12-18",
    formId: null,
    registeredCount: 0,
    published: true,
  },
  {
    id: "ev-sse",
    slug: "sse-classes",
    title: "SSE Classes (Groups 1 to 4)",
    description:
      "Sai Spiritual Education for children ages 6 to 17. Classes explore the five values through stories, music, group activities, and silent sitting. Parents register children once per school year.",
    bannerUrl: "/images/gallery-sse.svg",
    startsAt: "2026-07-12T15:00:00-07:00",
    endsAt: "2026-07-12T16:30:00-07:00",
    location: "Vancouver Sai Centre, Classrooms",
    capacity: 60,
    registrationEnabled: true,
    volunteerSignupEnabled: true,
    livestreamUrl: null,
    category: "sse",
    recurrence: "weekly",
    recurrenceUntil: "2026-12-13",
    formId: "form-sse",
    registeredCount: 47,
    published: true,
  },
  {
    id: "ev-guru-purnima",
    slug: "guru-purnima-2026",
    title: "Guru Purnima Celebration",
    description:
      "Our largest gathering of the summer. Bhajans, offerings of gratitude, a guest speaker, and a community dinner.\n\nThe hall seats 220 and filled up last year. Please register so we can plan seating and prasadam.",
    bannerUrl: "/images/gallery-festival.svg",
    startsAt: "2026-07-29T18:00:00-07:00",
    endsAt: "2026-07-29T21:30:00-07:00",
    location: "Vancouver Sai Centre, Main Hall",
    capacity: 220,
    registrationEnabled: true,
    volunteerSignupEnabled: true,
    livestreamUrl: "https://youtube.com/@vancouversaicentre/live",
    category: "special",
    recurrence: "none",
    recurrenceUntil: null,
    formId: "form-general",
    registeredCount: 184,
    published: true,
  },
  {
    id: "ev-sandwich-seva",
    slug: "sandwich-seva-july",
    title: "Sandwich Seva, Downtown Eastside",
    description:
      "We prepare 400 sandwich lunches at the centre in the morning, then hand them out in the Downtown Eastside along with water.\n\nVolunteers are needed for prep at 9 am and distribution at 11:30 am. Distribution volunteers must be 16 or older.",
    bannerUrl: "/images/gallery-seva.svg",
    startsAt: "2026-07-18T09:00:00-07:00",
    endsAt: "2026-07-18T13:30:00-07:00",
    location: "Meet at the Vancouver Sai Centre kitchen",
    capacity: 40,
    registrationEnabled: false,
    volunteerSignupEnabled: true,
    livestreamUrl: null,
    category: "service",
    recurrence: "monthly",
    recurrenceUntil: "2026-12-19",
    formId: "form-volunteer",
    registeredCount: 26,
    published: true,
  },
  {
    id: "ev-retreat",
    slug: "fall-retreat-2026",
    title: "Fall Family Retreat, Loon Lake",
    description:
      "Three days at Loon Lake Lodge in Maple Ridge. Morning sadhana, study sessions, family activities, and evening bhajans. Meals and accommodation are included. All meals are vegetarian.\n\nRegistration closes September 20.",
    bannerUrl: "/images/gallery-retreat.svg",
    startsAt: "2026-10-09T16:00:00-07:00",
    endsAt: "2026-10-11T14:00:00-07:00",
    location: "Loon Lake Lodge, Maple Ridge, BC",
    capacity: 120,
    registrationEnabled: true,
    volunteerSignupEnabled: true,
    livestreamUrl: null,
    category: "retreat",
    recurrence: "none",
    recurrenceUntil: null,
    formId: "form-retreat",
    registeredCount: 68,
    published: true,
  },
  {
    id: "ev-akhanda",
    slug: "akhanda-bhajan-2026",
    title: "Global Akhanda Bhajan",
    description:
      "Twenty-four hours of continuous devotional singing, joined by Sai centres around the world. Sign up for a singing hour, or just come and sit for as long as you like.",
    bannerUrl: "/images/gallery-akhanda.svg",
    startsAt: "2026-11-14T18:00:00-08:00",
    endsAt: "2026-11-15T18:00:00-08:00",
    location: "Vancouver Sai Centre, Main Hall",
    capacity: null,
    registrationEnabled: true,
    volunteerSignupEnabled: true,
    livestreamUrl: "https://youtube.com/@vancouversaicentre/live",
    category: "devotional",
    recurrence: "none",
    recurrenceUntil: null,
    formId: "form-general",
    registeredCount: 92,
    published: true,
  },
  {
    id: "ev-birthday",
    slug: "sai-birthday-2026",
    title: "Sri Sathya Sai Baba’s Birthday",
    description:
      "An evening of music and gratitude marking Baba’s birthday, with a children’s program from SSE, a community dinner, and the lighting of lamps.",
    bannerUrl: "/images/gallery-birthday.svg",
    startsAt: "2026-11-23T18:00:00-08:00",
    endsAt: "2026-11-23T21:30:00-08:00",
    location: "Vancouver Sai Centre, Main Hall",
    capacity: 250,
    registrationEnabled: true,
    volunteerSignupEnabled: true,
    livestreamUrl: "https://youtube.com/@vancouversaicentre/live",
    category: "special",
    recurrence: "none",
    recurrenceUntil: null,
    formId: "form-general",
    registeredCount: 41,
    published: true,
  },
  {
    id: "ev-blanket",
    slug: "blanket-drive-2026",
    title: "Winter Blanket and Coat Drive",
    description:
      "Our annual drive collecting blankets, coats, gloves, and sleeping bags for distribution before the cold sets in. Drop off donations any Sunday in October, or volunteer for the sorting and distribution weekend.",
    bannerUrl: "/images/gallery-blanket.svg",
    startsAt: "2026-10-25T10:00:00-07:00",
    endsAt: "2026-10-25T16:00:00-07:00",
    location: "Vancouver Sai Centre, Parking Level",
    capacity: null,
    registrationEnabled: false,
    volunteerSignupEnabled: true,
    livestreamUrl: null,
    category: "service",
    recurrence: "none",
    recurrenceUntil: null,
    formId: "form-volunteer",
    registeredCount: 18,
    published: true,
  },
];

export const demoForms: SaiForm[] = [
  {
    id: "form-general",
    title: "Event Registration",
    description: "Standard registration for centre events.",
    published: true,
    updatedAt: "2026-06-20T10:00:00-07:00",
    attachedEventIds: ["ev-guru-purnima", "ev-akhanda", "ev-birthday"],
    fields: [
      { id: "f1", type: "short-text", label: "Full name", helpText: "", required: true, options: [] },
      { id: "f2", type: "email", label: "Email", helpText: "We will send your confirmation here.", required: true, options: [] },
      { id: "f3", type: "phone", label: "Phone", helpText: "", required: false, options: [] },
      { id: "f4", type: "number", label: "Number of guests attending with you", helpText: "Including children.", required: true, options: [] },
      { id: "f5", type: "dropdown", label: "Will you join the community dinner?", helpText: "", required: true, options: ["Yes", "No", "Not sure yet"] },
      { id: "f6", type: "consent", label: "I consent to being photographed at this event", helpText: "Photos may appear in the centre’s gallery and newsletter.", required: false, options: [] },
    ],
  },
  {
    id: "form-sse",
    title: "SSE Annual Registration",
    description: "One registration per child, per school year.",
    published: true,
    updatedAt: "2026-06-01T10:00:00-07:00",
    attachedEventIds: ["ev-sse"],
    fields: [
      { id: "s1", type: "short-text", label: "Child’s full name", helpText: "", required: true, options: [] },
      { id: "s2", type: "date", label: "Child’s date of birth", helpText: "Used for group placement.", required: true, options: [] },
      { id: "s3", type: "short-text", label: "Parent / guardian name", helpText: "", required: true, options: [] },
      { id: "s4", type: "email", label: "Parent email", helpText: "", required: true, options: [] },
      { id: "s5", type: "phone", label: "Emergency contact number", helpText: "", required: true, options: [] },
      { id: "s6", type: "long-text", label: "Allergies or medical notes", helpText: "Leave blank if none.", required: false, options: [] },
      { id: "s7", type: "consent", label: "I consent to my child participating in SSE activities", helpText: "", required: true, options: [] },
    ],
  },
  {
    id: "form-volunteer",
    title: "Volunteer Signup",
    description: "Tell us where you can help.",
    published: true,
    updatedAt: "2026-06-15T10:00:00-07:00",
    attachedEventIds: ["ev-sandwich-seva", "ev-blanket"],
    fields: [
      { id: "v1", type: "short-text", label: "Full name", helpText: "", required: true, options: [] },
      { id: "v2", type: "email", label: "Email", helpText: "", required: true, options: [] },
      { id: "v3", type: "checkbox", label: "Which shifts can you take?", helpText: "", required: true, options: ["Morning prep (9:00 to 11:00)", "Distribution (11:30 to 1:30)", "Cleanup (1:30 to 2:30)"] },
      { id: "v4", type: "radio", label: "Can you drive supplies downtown?", helpText: "", required: true, options: ["Yes, I have a vehicle", "No"] },
      { id: "v5", type: "consent", label: "I have read the volunteer safety guidelines", helpText: "", required: true, options: [] },
    ],
  },
  {
    id: "form-retreat",
    title: "Fall Retreat Registration",
    description: "Registration for the Loon Lake family retreat.",
    published: true,
    updatedAt: "2026-06-28T10:00:00-07:00",
    attachedEventIds: ["ev-retreat"],
    fields: [
      { id: "r1", type: "short-text", label: "Full name", helpText: "", required: true, options: [] },
      { id: "r2", type: "email", label: "Email", helpText: "", required: true, options: [] },
      { id: "r3", type: "number", label: "Family members attending", helpText: "", required: true, options: [] },
      { id: "r4", type: "dropdown", label: "Accommodation preference", helpText: "", required: true, options: ["Shared lodge room", "Family cabin", "Day visitor (no overnight)"] },
      { id: "r5", type: "long-text", label: "Dietary requirements", helpText: "All meals are vegetarian. Note allergies here.", required: false, options: [] },
      { id: "r6", type: "file", label: "Signed waiver (PDF)", helpText: "Download the waiver from the Resources page.", required: true, options: [] },
    ],
  },
];

export const demoBhajans: Bhajan[] = [
  {
    id: "bh-1",
    title: "Ganesha Sharanam",
    meaning: "I take refuge in Lord Ganesha, remover of obstacles.",
    language: "Sanskrit",
    tempo: "medium",
    category: "Ganesha",
    notes: "Traditional opening bhajan. Begin slowly, double the tempo on the repeat.",
    lyrics:
      "Ganesha Sharanam Sharanam Ganesha\nGanesha Sharanam Sharanam Ganesha\nGam Gam Ganapathi Sharanam Ganesha\nGam Gam Ganapathi Sharanam Ganesha\nJai Ganesha Jai Jai Gananatha",
    audioUrl: null,
    videoUrl: null,
  },
  {
    id: "bh-2",
    title: "Sathya Sai Ram Om Sai Ram",
    meaning: "Chanting the name of Sai Ram, embodiment of truth.",
    language: "Sanskrit",
    tempo: "medium",
    category: "Sai",
    notes: "A centre favourite. Invite the congregation to clap on the fast repeat.",
    lyrics:
      "Om Sai Ram Om Sai Ram\nSathya Sai Ram Om Sai Ram\nOm Sai Ram Om Sai Ram\nParthi Vihari Om Sai Ram\nPrema Swaroopa Om Sai Ram",
    audioUrl: null,
    videoUrl: null,
  },
  {
    id: "bh-3",
    title: "Subrahmanyam Subrahmanyam",
    meaning: "Salutations to Lord Subrahmanya, the six-faced divine general.",
    language: "Sanskrit",
    tempo: "fast",
    category: "Subrahmanya",
    notes: "Builds quickly. Watch the lead singer for the tempo change.",
    lyrics:
      "Subrahmanyam Subrahmanyam\nShanmukhanatha Subrahmanyam\nShiva Shiva Shiva Shiva Subrahmanyam\nHara Hara Hara Hara Subrahmanyam",
    audioUrl: null,
    videoUrl: null,
  },
  {
    id: "bh-4",
    title: "He Shiva Shankara Namami Shankara",
    meaning: "O Shiva, Shankara, I bow to you, bestower of auspiciousness.",
    language: "Sanskrit",
    tempo: "slow",
    category: "Shiva",
    notes: "Meditative. Keep the harmonium soft under the first verse.",
    lyrics:
      "He Shiva Shankara Namami Shankara\nShiva Shankara Shambho\nHe Girijapathi Bhavani Shankara\nShiva Shankara Shambho",
    audioUrl: null,
    videoUrl: null,
  },
  {
    id: "bh-5",
    title: "Rama Rama Rama Sita",
    meaning: "Chanting the names of Rama and Sita together.",
    language: "Sanskrit",
    tempo: "medium",
    category: "Rama",
    notes: "",
    lyrics:
      "Rama Rama Rama Sita\nRama Nama Bhajare\nKrishna Krishna Krishna Radha\nKrishna Nama Bhajare",
    audioUrl: null,
    videoUrl: null,
  },
  {
    id: "bh-6",
    title: "Govinda Krishna Jai",
    meaning: "Victory to Govinda, victory to Krishna.",
    language: "Sanskrit",
    tempo: "fast",
    category: "Krishna",
    notes: "Good for children’s sessions. Simple call and response.",
    lyrics:
      "Govinda Krishna Jai\nGopala Krishna Jai\nGopala Bala Bala Radha\nKrishna Jai\nGovinda Krishna Jai\nGopala Krishna Jai",
    audioUrl: null,
    videoUrl: null,
  },
  {
    id: "bh-7",
    title: "Om Namah Shivaya",
    meaning: "Salutations to Shiva, the five-syllable mantra.",
    language: "Sanskrit",
    tempo: "slow",
    category: "Shiva",
    notes: "Often used to close the session before aarti.",
    lyrics:
      "Om Namah Shivaya\nOm Namah Shivaya\nOm Namah Shivaya\nShivaya Namah Om\nHara Hara Hara Hara Namah Shivaya",
    audioUrl: null,
    videoUrl: null,
  },
  {
    id: "bh-8",
    title: "Allah Ho Akbar",
    meaning: "God is great. A bhajan honouring the unity of all faiths.",
    language: "Urdu",
    tempo: "medium",
    category: "Sarva Dharma",
    notes: "Sung during interfaith programs and Sarva Dharma celebrations.",
    lyrics:
      "Allah Ho Akbar Allah Ho Akbar\nLa Ilaha Illallah\nMaula Salim Ala Ho Akbar\nLa Ilaha Illallah",
    audioUrl: null,
    videoUrl: null,
  },
  {
    id: "bh-9",
    title: "Love Is My Form",
    meaning: "A song of Baba’s message in English.",
    language: "English",
    tempo: "slow",
    category: "Sai",
    notes: "English bhajan. Often sung at public programs for newcomers.",
    lyrics:
      "Love is my form, Truth is my breath\nBliss is my food\nMy life is my message\nExpansion is my life\nNo season for love, No reason for love\nNo birth, no death",
    audioUrl: null,
    videoUrl: null,
  },
  {
    id: "bh-10",
    title: "Jai Jai Jai Gananayaka",
    meaning: "Victory to the leader of the ganas, Lord Ganesha.",
    language: "Sanskrit",
    tempo: "fast",
    category: "Ganesha",
    notes: "",
    lyrics:
      "Jai Jai Jai Gananayaka\nJai Jai Vighna Vinashaka\nJai Shubhakara Jai Mangala Kara\nJai Jai Vidya Buddhi Pradayaka",
    audioUrl: null,
    videoUrl: null,
  },
];

export const demoResources: Resource[] = [
  {
    id: "rs-1",
    title: "Sadhana: The Inward Path, Study Guide",
    description: "Chapter by chapter discussion questions for this season’s study circle.",
    kind: "study",
    url: "#",
    tags: ["study circle", "sadhana"],
    membersOnly: false,
    createdAt: "2026-06-10",
  },
  {
    id: "rs-2",
    title: "Guru Purnima Discourse (1996)",
    description: "Baba’s Guru Purnima discourse on the guru within. Audio, 48 minutes.",
    kind: "discourse",
    url: "#",
    tags: ["guru purnima", "discourse"],
    membersOnly: false,
    createdAt: "2026-06-22",
  },
  {
    id: "rs-3",
    title: "Centre Bhajan Book (2026 Edition)",
    description: "The full centre songbook with 214 bhajans, transliterations, and meanings.",
    kind: "pdf",
    url: "#",
    tags: ["bhajans", "songbook"],
    membersOnly: false,
    createdAt: "2026-01-15",
  },
  {
    id: "rs-4",
    title: "SSE Group 2 Term Materials",
    description: "Lesson plans and take-home activities for ages 9 to 12, fall term.",
    kind: "study",
    url: "#",
    tags: ["sse", "children"],
    membersOnly: true,
    createdAt: "2026-06-01",
  },
  {
    id: "rs-5",
    title: "Retreat Waiver Form",
    description: "Required signed waiver for the Loon Lake fall retreat.",
    kind: "pdf",
    url: "#",
    tags: ["retreat", "forms"],
    membersOnly: false,
    createdAt: "2026-06-28",
  },
  {
    id: "rs-6",
    title: "Harmonium Basics, Video Series",
    description: "A five-part video series for beginning harmonium players in the bhajan group.",
    kind: "video",
    url: "#",
    tags: ["bhajans", "music", "tutorial"],
    membersOnly: true,
    createdAt: "2026-05-12",
  },
  {
    id: "rs-7",
    title: "Silent Sitting for Families, Audio Series",
    description: "Guided five-minute silent sitting exercises used in SSE, for practice at home.",
    kind: "audio",
    url: "#",
    tags: ["sse", "meditation", "families"],
    membersOnly: false,
    createdAt: "2026-04-03",
  },
  {
    id: "rs-8",
    title: "Sunday Bhajans Recording Archive",
    description: "Recordings of recent Sunday sessions for singers learning new bhajans.",
    kind: "bhajan",
    url: "#",
    tags: ["bhajans", "recordings"],
    membersOnly: true,
    createdAt: "2026-06-29",
  },
];

export const demoAlbums: Album[] = [
  {
    id: "al-1",
    title: "Easwaramma Day 2026",
    description: "The children’s program and community lunch on May 6.",
    eventId: null,
    coverUrl: "/images/gallery-festival.svg",
    date: "2026-05-06",
    photos: [
      { id: "p1", url: "/images/gallery-festival.svg", caption: "The hall decorated for the day", width: 1200, height: 800 },
      { id: "p2", url: "/images/gallery-sse.svg", caption: "SSE Group 1 performing", width: 800, height: 1000 },
      { id: "p3", url: "/images/gallery-bhajan-hall.svg", caption: "Evening bhajans", width: 1200, height: 900 },
      { id: "p4", url: "/images/gallery-lamp.svg", caption: "Lighting the lamps", width: 800, height: 1200 },
      { id: "p5", url: "/images/gallery-community.svg", caption: "Community lunch", width: 1200, height: 800 },
    ],
  },
  {
    id: "al-2",
    title: "Sandwich Seva, June",
    description: "Four hundred lunches prepared and shared in the Downtown Eastside.",
    eventId: "ev-sandwich-seva",
    coverUrl: "/images/gallery-seva.svg",
    date: "2026-06-20",
    photos: [
      { id: "p6", url: "/images/gallery-seva.svg", caption: "The morning prep line", width: 1200, height: 800 },
      { id: "p7", url: "/images/gallery-community.svg", caption: "Volunteers heading out", width: 900, height: 1200 },
      { id: "p8", url: "/images/gallery-hands.svg", caption: "Many hands", width: 1200, height: 800 },
    ],
  },
  {
    id: "al-3",
    title: "YA Spring Retreat",
    description: "A weekend of study and rest at Golden Ears.",
    eventId: null,
    coverUrl: "/images/gallery-retreat.svg",
    date: "2026-04-18",
    photos: [
      { id: "p9", url: "/images/gallery-retreat.svg", caption: "Morning sadhana by the lake", width: 1200, height: 800 },
      { id: "p10", url: "/images/gallery-ya.svg", caption: "Study session", width: 800, height: 1000 },
      { id: "p11", url: "/images/gallery-lamp.svg", caption: "Evening aarti", width: 900, height: 1200 },
    ],
  },
];

// Email notification history (used by the notification manager and analytics).
export const demoAnnouncements: Announcement[] = [
  {
    id: "an-1",
    title: "Guru Purnima registration is open",
    body: "Registration for our July 29 Guru Purnima celebration is open. The hall seats 220 and filled up last year, so please register early.",
    topics: ["devotional", "major-events"],
    sentAt: "2026-07-01T09:00:00-07:00",
    createdAt: "2026-06-30T14:00:00-07:00",
    recipients: 412,
    openRate: 0.64,
  },
  {
    id: "an-2",
    title: "Fall retreat: registration closes Sept 20",
    body: "68 of 120 spots are taken for the Loon Lake retreat. Family cabins are nearly full. Register soon if you would like one.",
    topics: ["retreats", "major-events"],
    sentAt: "2026-06-25T10:00:00-07:00",
    createdAt: "2026-06-24T16:00:00-07:00",
    recipients: 388,
    openRate: 0.58,
  },
  {
    id: "an-3",
    title: "July sandwich seva: drivers needed",
    body: "We are short three drivers for the July 18 sandwich seva. If you can transport supplies downtown, please add yourself under Volunteer Signups.",
    topics: ["service"],
    sentAt: "2026-07-03T08:30:00-07:00",
    createdAt: "2026-07-02T19:00:00-07:00",
    recipients: 156,
    openRate: 0.71,
  },
];

export const demoProfiles: Profile[] = [
  {
    id: "user-demo",
    fullName: "Aadavn Nimalthas",
    email: "aadavn@example.com",
    role: "administrator",
    interests: ["devotional", "study-circle", "major-events", "retreats"],
    joinedAt: "2019-03-12",
    avatarUrl: null,
  },
  { id: "u2", fullName: "Arun Krishnan", email: "arun@example.com", role: "wing-lead", interests: ["service", "major-events"], joinedAt: "2017-09-02", avatarUrl: null },
  { id: "u3", fullName: "Meera Naidoo", email: "meera@example.com", role: "volunteer", interests: ["sse", "education"], joinedAt: "2021-01-20", avatarUrl: null },
  { id: "u4", fullName: "Daniel Chen", email: "daniel@example.com", role: "member", interests: ["young-adults", "study-circle"], joinedAt: "2023-11-05", avatarUrl: null },
  { id: "u5", fullName: "Lakshmi Pillai", email: "lakshmi@example.com", role: "executive", interests: ["devotional", "major-events", "retreats"], joinedAt: "2015-06-14", avatarUrl: null },
  { id: "u6", fullName: "Sofia Alvarez", email: "sofia@example.com", role: "member", interests: ["service"], joinedAt: "2024-04-22", avatarUrl: null },
  { id: "u7", fullName: "Ravi Shankar", email: "ravi@example.com", role: "volunteer", interests: ["devotional", "service"], joinedAt: "2020-08-30", avatarUrl: null },
];

export const demoRegistrations: Registration[] = [
  {
    id: "rg-1",
    eventId: "ev-guru-purnima",
    userId: "user-demo",
    kind: "attendee",
    status: "registered",
    answers: { guests: 3, dinner: "Yes" },
    createdAt: "2026-07-01T10:12:00-07:00",
    eventTitle: "Guru Purnima Celebration",
    eventStartsAt: "2026-07-29T18:00:00-07:00",
    userName: "Aadavn Nimalthas",
    userEmail: "aadavn@example.com",
  },
  {
    id: "rg-2",
    eventId: "ev-retreat",
    userId: "user-demo",
    kind: "attendee",
    status: "registered",
    answers: { family: 4, accommodation: "Family cabin" },
    createdAt: "2026-06-29T20:44:00-07:00",
    eventTitle: "Fall Family Retreat, Loon Lake",
    eventStartsAt: "2026-10-09T16:00:00-07:00",
    userName: "Aadavn Nimalthas",
    userEmail: "aadavn@example.com",
  },
  {
    id: "rg-3",
    eventId: "ev-sandwich-seva",
    userId: "user-demo",
    kind: "volunteer",
    status: "registered",
    answers: { shifts: ["Morning prep (9:00 to 11:00)"] },
    createdAt: "2026-07-02T08:15:00-07:00",
    eventTitle: "Sandwich Seva, Downtown Eastside",
    eventStartsAt: "2026-07-18T09:00:00-07:00",
    userName: "Aadavn Nimalthas",
    userEmail: "aadavn@example.com",
  },
  { id: "rg-4", eventId: "ev-guru-purnima", userId: "u2", kind: "attendee", status: "registered", answers: {}, createdAt: "2026-07-01T11:00:00-07:00", eventTitle: "Guru Purnima Celebration", eventStartsAt: "2026-07-29T18:00:00-07:00", userName: "Arun Krishnan", userEmail: "arun@example.com" },
  { id: "rg-5", eventId: "ev-guru-purnima", userId: "u3", kind: "attendee", status: "checked-in", answers: {}, createdAt: "2026-06-30T09:00:00-07:00", eventTitle: "Guru Purnima Celebration", eventStartsAt: "2026-07-29T18:00:00-07:00", userName: "Meera Naidoo", userEmail: "meera@example.com" },
  { id: "rg-6", eventId: "ev-guru-purnima", userId: "u4", kind: "attendee", status: "waitlisted", answers: {}, createdAt: "2026-07-04T22:10:00-07:00", eventTitle: "Guru Purnima Celebration", eventStartsAt: "2026-07-29T18:00:00-07:00", userName: "Daniel Chen", userEmail: "daniel@example.com" },
  { id: "rg-7", eventId: "ev-sandwich-seva", userId: "u7", kind: "volunteer", status: "registered", answers: {}, createdAt: "2026-07-03T07:45:00-07:00", eventTitle: "Sandwich Seva, Downtown Eastside", eventStartsAt: "2026-07-18T09:00:00-07:00", userName: "Ravi Shankar", userEmail: "ravi@example.com" },
  { id: "rg-8", eventId: "ev-retreat", userId: "u5", kind: "attendee", status: "registered", answers: {}, createdAt: "2026-06-26T12:30:00-07:00", eventTitle: "Fall Family Retreat, Loon Lake", eventStartsAt: "2026-10-09T16:00:00-07:00", userName: "Lakshmi Pillai", userEmail: "lakshmi@example.com" },
];

/** Demo signed-in user (used when Supabase auth is not configured). */
export const demoCurrentUser = demoProfiles[0];
