-- Intentionally minimal. The system starts empty in production:
-- events, posts, forms, resources, books, albums, and bhajans are all
-- created through the admin console.
--
-- Structural rows (the four wings) are inserted by
-- migrations/0003_production_cms.sql.
--
-- After your first sign-up, promote your account:
--   update public.profiles set role = 'administrator' where email = 'you@example.com';
